name: Pytest flask and postgresql

on:
  push:
    branches: [ feature/unittesting ]

jobs:
  test_package:
    name: Pytest flask and postgresql
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
        - uses: actions/checkout@v3
        - name: Setup python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
            architecture: x64
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run PyTest
          run: |
            flask db upgrade
            pytest
          env:
            DBNAME: postgres
            DBHOST: localhost
            DBUSER: postgres
            DBPASS: postgres
            SECRET_KEY: flask-insecure-key-${{ github.run_id }}-${{ github.run_attempt }}
            FLASK_TEST: true
