name: Static Code Check

on:
  push:
    branches: [ feature/unittesting ]

jobs:
  test_package:
    name: Static code check
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
        - name: Cache
          uses: actions/cache@v2.1.8
          with: 
            path: '*'
            key: 'CacheKey_static_code_check'
        - uses: actions/checkout@v3
        - name: Setup python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
            architecture: x64
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install flake8
        - name: Look for major issues with flake8
          run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        - name: Make sure Python code is all compilable
          run: |
            python -m compileall . -f
        - name: Run Flask server
          run: |
            flask db upgrade
            flask run &
          env:
            DBNAME: postgres
            DBHOST: localhost
            DBUSER: postgres
            DBPASS: postgres
            SECRET_KEY: flask-insecure-key-${{ github.run_id }}-${{ github.run_attempt }}
            FLASK_RUN: true
